version: '2'
services:
  jhipstersampleapplication-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/jhipsterSampleApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterSampleApplication
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
